<?php
/** @var \Custom\FeaturedProducts\Block\FeaturedProducts $block */

$_productCollection = $block->getFeaturedProducts(5);

if (count($_productCollection) > 0): ?>
<section class="section__content">
    <div class="block-featured">
        <h2 class="block-featured__title">
            <span class="block-featured__title-span">
                <?= __('Featured Products') ?>
            </span>
        </h2>

        <div class="product-list">
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                    $_id = $_product->getId();
                    $_productCard = $block->getProductCard($_id);

                    if($_productCard): ?>
                        <?= $_productCard; ?>
                    <?php endif;
                ?>
            <?php endforeach; ?>
        </div>
    </div>
</section>
<?php endif; ?>
