<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="header__banner">
    <div class="wrapper">
        <p class="header__banner-text">This Marketplace is for PSE&G New Jersey Residential Customer Only</p>

        <div class="header__banner-links">
            <a class="header__banner-link" href="/contact-us">Contact Us</a>
            <a class="header__banner-link" href="/faqs">FAQs</a>
        </div>
    </div>
</div>